version: '3.8'

services:
  web:
    build: .
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 80"
    restart: always
    expose:
      - 80
    volumes:
      - images_data:/images
    environment:
      - POSTGRES_URL_DOCKER=postgresql://gb_user:password@db:5432/guidebook
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`YOUR.DOMAIN`)"
      - "traefik.http.routers.fastapi.tls=true"
      - "traefik.http.routers.fastapi.tls.certresolver=letsencrypt"
  bot:
    build: .
    command: "python bot.py"
    restart: always
    environment:
      - POSTGRES_URL_DOCKER=postgresql://gb_user:password@db:5432/guidebook
      - VK_GROUP_TOKEN=
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=gb_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=guidebook
  traefik:
    build:
      context: .
      dockerfile: Dockerfile.traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik-public-certificates:/certificates"
    labels:
      - "traefik.enable=true"

volumes:
  postgres_data:
  images_data:
  traefik-public-certificates: