"""Add month income

Revision ID: 317cd5f61f58
Revises: b27704b3b268
Create Date: 2022-11-24 19:01:33.042938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '317cd5f61f58'
down_revision = 'b27704b3b268'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('incomeMonth', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'images', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_column('cities', 'incomeMonth')
    # ### end Alembic commands ###
