"""add owner to city

Revision ID: 60923c9e2da0
Revises: f63a7102d013
Create Date: 2022-11-06 19:26:45.619260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60923c9e2da0'
down_revision = 'f63a7102d013'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_owner', 'cities', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_owner', 'cities', type_='foreignkey')
    op.drop_column('cities', 'owner_id')
    # ### end Alembic commands ###
